### ISSUE TITLE
Items.otb version:

### ISSUE THREAD

**Issue by JotaCampagnolo** [brewsterl/RealOTX-7.72#10]
When you compile the server, the new distro can't load items.otb. I've compiled following the compile tutorial on Github.
Image: [image](http://i.imgur.com/iqJOuB9.png)

**Comment by JotaCampagnolo** [comment]
Solved. You need to change the directory from data/items/77 to data/items/74, or change it on source code.

**Comment by brewsterl** [comment]
No, You need compile with flag 

> _MULTIPLATFORM77


You're compiling in the 7.4 version (without flag _MULTIPLATFORM77) and that's why this error occurs. RealOtx is compatible with version 7.72

**Comment by JotaCampagnolo** [comment]
Ok, thanks.
