### ISSUE TITLE
New Outfits:

### ISSUE THREAD

**Issue by JotaCampagnolo** [brewsterl/RealOTX-7.72#12]
I've tried to add a new outfit, then i add in outfits.xml the outfit and his looktype... But, in game it doesn't work. There is some issue here or im doing some wrong?

**Comment by brewsterl** [comment]
https://github.com/brewsterl/RealOTX-7.72/blob/master/sources/protocolgame.cpp#L2243-L2249

It requires editing sources & spr besides outfits.xml

**Comment by JotaCampagnolo** [comment]
Ok, i'll try it. Thanks

**Comment by JotaCampagnolo** [comment]
Can you help me? I just want to add the GM outfit to gamemasters, but i read the code and really dont understand how...

**Comment by brewsterl** [comment]
If you only want to use the outfit gm. Use the command:

> /newtype 75

**Comment by JotaCampagnolo** [comment]
Yeah, i know that, but i need to add new outfits, and i doesnt understand how to do it... :/
