### ISSUE TITLE
Amulet of loss/bless

### ISSUE THREAD

**Issue by Felipe1993** [brewsterl/RealOTX-7.72#13]
Hello

well amulet of loss don't dissapear 
to have bless and dont loss things you have to use amulet of loss

**Comment by brewsterl** [comment]
Se que hablas español y te lo explicare de manera clara, no es un bug, ,estoy seguro que el amulet of loss lo creaste con el gm. Al crear un amuleto de esos, automaticamente sale con 100 cargas. Compralo en un npc y el amulet desaparece. Con respecto al bless system, es el que corresponde a esa epoca, donde perdias objetos asi tengas bless.. Si no me crees aqui puedes confirmar esta informacion:
