### ISSUE TITLE
Itens Loss when die:

### ISSUE THREAD

**Issue by JotaCampagnolo** [brewsterl/RealOTX-7.72#14]
When i was testing rookgaard, i've noticed that backpack doesn't drop... Is that because i was in rookgaard? If yes, when i change that? If not, how can i fix it?
Another problem i've found is that when your backpack is full, but you have 15 gps in your backpack for example, you cant even collect more gold coins to stack in the 15 gps you have on your backpack...

**Comment by brewsterl** [comment]
vocations.xml for no vocations (none):

> droploot="no"

about the stack maybe it is a problem of tfs 0.3.7

**Comment by JotaCampagnolo** [comment]
Ok, thank you ^^
