### ISSUE TITLE
Problema con las casas

### ISSUE THREAD

**Issue by Felipe1993** [brewsterl/RealOTX-7.72#15]
Hola @brewsterl nose si sera un bug pero al usar comando!buyhouse /buyhouse !buy house /buy house
me dice que debo estar parado en frente de la puerta aunque si lo este haciendo creo que es porque no estan los talkactions script o no son los que corresponden 
me podrias pasar los correspodientes porfavor? o si es un bug dime 
saludos

**Comment by Felipe1993** [comment]
ando usando el otx cast con mysql nose si eso implica algo

**Comment by brewsterl** [comment]
hazle look a la door y ve si te marca la casa, si no, tendras que agregar una a una cada puerta de cada casa del map. generalmente esto ocurre cuando utilizan el RME y no le dan a guardar solo  le dan exit, y el mapa se "daña" y tanto algunas houses, , como los teleports de dañan..

**Comment by Felipe1993** [comment]
@brewsterl las casas si funcionan sale el precio,nombre y todo lo que no sirve son los comandos para comprar la casa creo que los scripts no estan, me los podrias dar?
<talkaction access="0-4" words="alana res;/buyhouse" filter="word-spaced" event="function" value="houseBuy"/>
	<talkaction access="0-4" words="alana grav;/sellhouse" filter="word-spaced" event="function" value="houseSell"/>
	<talkaction access="0-4" words="alana sio" filter="word-spaced" event="function" value="houseKick"/>
	<talkaction access="0-4" words="aleta grav" filter="word-spaced" event="function" value="houseDoorList"/>
	<talkaction access="0-4" words="aleta sio" filter="word-spaced" event="function" value="houseGuestList"/>
	<talkaction access="0-4" words="aleta som" filter="word-spaced" event="function" value="houseSubOwnerList"/>
	<talkaction access="0-4" words="alana som;/leavehouse" filter="word-spaced" event="script" value="leavehouse.lua"/>

**Comment by Felipe1993** [comment]
houseBuy
houseSell
houseKick
houseDoorList
houseDoorGuest
houseSubOwnerList
leavehouse
revise y esos scripts no estan porfa ayudame saludos

**Comment by Felipe1993** [comment]
busque otros les edite el nombre ninguno me sirvio :/

**Comment by brewsterl** [comment]
? esas funciones estan en el codigo y funciona perfectamente. El problema eres tu que algo haces mal
