### ISSUE TITLE
Walk + Runes:

### ISSUE THREAD

**Issue by JotaCampagnolo** [brewsterl/RealOTX-7.72#17]
When you are walking, you cant use any rune...

**Comment by brewsterl** [comment]
This should be true. runes to use while walking is a superior version, or am I wrong?

**Comment by JotaCampagnolo** [comment]
I think even in this low versions you could walk and use runes... I remember walk and use gfbs, hmms...

**Comment by brewsterl** [comment]
This should not be so, but if so you want... try:

https://github.com/brewsterl/RealOTX-7.72/blob/master/sources/player.cpp#L1609
Change with:
> //setNextAction(OTSYS_TIME() + getStepDuration(dir));
